### ISSUE TITLE
Version 2.0.2 missing from PyPI

### ISSUE THREAD

**Issue by jrstjohn** [briancline/crm114-python#6]
A tarball of version 2.0.2 is not available on PyPI. Only version 2.0.1 can be found there.

https://pypi.python.org/pypi/crm114

**Comment by briancline** [comment]
Hey Jason,

Sorry for the oversight on my part. I've done an sdist upload to PyPI for 2.0.2. If you have any trouble retrieving it, let me know and I'll look into it further.

Thanks!

**Comment by jrstjohn** [comment]
Thanks for the quick response!
